<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>EstateAgency Bootstrap Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    @include('folderstyles');
    @include('header2');
    <!--/ Nav End /-->



    <!--/ Intro Single start /-->
    <section class="intro-single">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="title-single-box">
                        <h1 class="title-single">Tax-Returns</h1>
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="/">Home</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="income-tax">Income-Tax</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Tax-Return
                            </li>

                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!--/ Intro Single End /-->

    <!--/  content start /-->
    <div class="container section-t8 left-color">
        <h4>Introduction on Income Tax</h4>

        <p>In India, there are two types of taxes one is direct tax which is directly levied upon the income of the
            individual and another is indirect tax which is levied indirectly upon an individual. Example of direct tax
            is income tax and of indirect tax is Goods and Services Tax, service tax etc.</p>
        <p>Every individual who receives income in India is subject to income tax under the Income Tax Act, 1961. Under
            Income Tax Act there can be income from 5 different heads which are Income from salary, house property,
            capital gains, business and profession and other sources.Income of individuals, Hindu undivided family,
            association of person, body of individuals firms and companies are taxed under the Income tax act.</p>



        <h4>What is Income Tax Return</h4>

        <p>Income Tax Return is a form in which the taxpayer whether it be an individual or firm or Hindu undivided
            family, discloses details of its income, claims exemptions and deductions which are applicable on it and the
            amount of tax payable on such income. The Income Tax Return also reflects the amount of taxes paid by the
            taxpayer.</p>
        <p>Income tax return is form in which the taxpayer files data and information regarding his income and tax
            payable thereon at the end of every financial year.</p>

        <h4>What is Income Tax eFiling</h4>

        <p>Income Tax can be filed by the two way i.e is the Online Method and another offline Method. Now as per the
            Government Instructions all the income tax return will be filed only through ITR eFiling Method.</p>
        <p>So in the following cases, ITR Online eFiling is Mandatory –<br>
            1) if your taxable income is more than 5 lakh rupees in a year or if you want to claim any refund.<br>
            2) if your accounts will required auditing under section 44 AB and Return would be furnished in ITR 3 or ITR
            4</p>
        <p>Only these person can use the offline ITR Filing Method –<br>
            1) if your taxable income is less than 5 lakh rupees in the year and not required to claim any refund.<br>
            2) An individual who’s age 80 years or more during the filing of Income Tax Return.</p>


        <h2>Types of ITR forms</h2>
        <p>Depending on the type of income that is generated by the taxpayer, the form that must be submitted will be
            different. The various forms can be downloaded from the official website of the income tax department
            https://www.incometaxindia.gov.in/pages/downloads/income-tax-return.aspx. The different types of ITR forms
            that are available are mentioned below: </p>
        <div>
            <table>
                <thead>
                    <tr>
                        <th class="table-header"><strong>ITR Form Name</strong></th>
                        <th class="table-header"><strong>Applicability</strong></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            ITR-1
                        </td>
                        <td>
                            The form must be used by individuals who make an annual income of less than Rs.50 lakh via
                            pension or salary and from only one house property.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-2
                        </td>
                        <td>
                            The form must be used by shareholders of private companies, Directors of Companies,
                            Non-Resident Indians (NRIs), or individuals who make an income via capital gains, from two
                            or more
                            house properties, and from foreign sources. However, the income of the individual must be
                            more than Rs.50 lakh.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-3
                        </td>
                        <td>
                            The form must be used by individuals who run a proprietorship or are professionals in India.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-4
                        </td>
                        <td>
                            Individuals who are under the presumptive taxation scheme must use this form. In order for
                            individuals to join the scheme, they must earn less than Rs.50 lakh from professional income
                            or less than Rs.2 crore from business income.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-5
                        </td>
                        <td>
                            In order for association and body of individuals, Limited Liability Partnerships (LLPs), and
                            partnership firms to report their income and tax computation, this form must be used.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-6
                        </td>
                        <td>
                            Companies that are registered in India must use this form.
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ITR-7
                        </td>
                        <td>
                            In case entities are claiming an exemption as universities or colleges, scientific research
                            institutions, political parties, and religious or charitable trusts, this form must be used.
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2>Importance of ITR Filing</h2>
        <p>Currently(FY 2019-20), is mandatory for one to file income tax returns in India if the following conditions
            are applicable -</p>
        <ul>
            <li>If the gross total annual income (before deductions under 80C to 80U) is Rs. 2,50,000 (for ages less
                than 60 years), Rs. 3,00,000 (for ages 60 years but less than 80 years) and Rs. 5,00,000 (for ages 80
                years and above)</li>
            <li>If it’s a company or firm, irrespective of the profit or loss made in a financial year</li>
            <li>If a tax refund needs to be claimed</li>
            <li>If a loss under a head of income needs to be carried forward</li>
            <li>If being a resident of India, one has an asset or financial interest in any entity located outside India
            </li>
            <li>If being a resident of India, one is a signing authority in a foreign account</li>
            <li>If one receives income derived from property held under a trust for charitable or religious purposes or
                a political party or a research association, news agency, educational or medical institution, trade
                union, a not for profit university or educational institution, a hospital, infrastructure debt fund, any
                authority, body or trust</li>
            <li>If one is applying for a loan or a visa</li>
            <li>If an NRI derives any or all of his/her income through sources in India, that income is liable to be
                taxable in India, and income tax returns for the same will be necessary.</li>
        </ul>
        <p><strong>With the implementation of e-filing of Income Tax Returns, the following cases will require an
                e-filing Income Tax:</strong> </p>
        <ul>
            <li>In case a refund is required</li>
            <li>In case the gross total annual income exceeds Rs. 5,00,000</li>
            <li>In case an income tax refund is required</li>
            <li>ITR-3, 4,5,6,7 have to be mandatorily e-filed</li>
        </ul>
        <h4>Income Tax E-filing Due Date</h4>

        <p>The due date of E-filling of income tax returns depends upon the taxpayer. If the taxpayer is individual,
            body of individuals, association of persons, Hindu undivided family then the due date for filling income tax
            return is August 31 every financial year. However, for business and companies which require audit the date
            for filling income tax return is September 30 every financial year. For any person who is required to
            furnish report in form No. 32CEB under section 92E the date for filling income tax return is November 30
            every financial year. If the taxpayer does not file the income tax return in time, then he will have to pay
            the late fee along with the tax payable.</p>

        <h4>What are the Benefits or Advantages of Income Tax Return Filing?</h4>

        <p>There are various advantages of filling an Income Tax Return which are as follows:<br>
            <strong><br>
                #1 Loan :&nbsp;</strong>An individual who has filed INCOME TAX RETURN can help him in availing
            vehicle or home loans as many banks asks for a copy of Income tax Returns.<br>
            <strong><br>
                #2&nbsp;To claim refund :&nbsp;</strong>If any refund claim is due to you form the income tax
            department you will have to file return in order to receive the refund claim.</p>
        <p><strong>#3&nbsp;To carry forward losses :</strong>&nbsp;If you are incurring any capital losses, you
            cannot carry forward the same id you have not filed an income tax return.</p>
        <p><strong>#4 Visa processing :</strong>&nbsp;If you are planning to travel overseas, there might be
            chances that at the time of visa interview you are required to furnish your Income tax return
            receipt of last years.</p>
        <p><strong>#5 Buying high life insurance policy :</strong>&nbsp;If you are planning to buy any life
            insurance policy like of Rs. 50 lakh or Rs. 1 Crore, then the life insurance company like LIC might
            ask for your Income Tax Return receipts of previous years.</p>
        <p><strong>#6 Government tender :&nbsp;</strong>If you are planning to obtain any government tender in
            future, you should have your income tax returns receipts of the last few years. This is required to
            support your financial status.</p>

        <h4>What is Income Tax Slabs for the Financial Year 2018-19</h4>

        <p>The tax slabs are different on the basis of the tax payer like individual, senior citizen, company
            etc.</p>
        <p>Tax Slab for Individuals and Hindu undivided family</p>
        <ol>
            <li><strong>Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; –&nbsp; &nbsp;&nbsp;</strong>Upto Rs.
                2,50,000</li>
        </ol>
        <p>Rate of
            Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp; &nbsp;&nbsp; – &nbsp; No Tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 2. Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –</strong>&nbsp;&nbsp; Rs 2,50,000 to Rs 5,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of Tax &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp; &nbsp;&nbsp; –&nbsp;&nbsp;&nbsp; 5%</strong><br>
            <strong>Health &amp; education cess&nbsp; –&nbsp;&nbsp;</strong>4% of income tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 3. Income &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; –&nbsp;&nbsp;</strong>Rs 5,00,000
            to Rs. 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of Tax &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; –&nbsp;</strong>20%<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Health &amp; education cess&nbsp;&nbsp;
                –&nbsp;</strong>4% of income tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 4.
                Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;&nbsp;</strong>More than Rs. 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of
                Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;</strong>30%<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Health &amp; education cess &nbsp;
                &nbsp; –&nbsp;</strong>4% of income tax</p>
        <p>For Senior Citizen (age above 60 years and below 80 years)</p>
        <ol>
            <li><strong>Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; –&nbsp; &nbsp;&nbsp;</strong>Upto Rs
                3,00,000</li>
        </ol>
        <p>Rate of
            Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp; &nbsp;&nbsp; – &nbsp; No Tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 2. Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –</strong>&nbsp;&nbsp; Rs 3,00,000 – Rs 5,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of Tax &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp; &nbsp;&nbsp; –&nbsp;&nbsp;&nbsp; 5%</strong><br>
            <strong>Health &amp; education cess&nbsp; –&nbsp;&nbsp;</strong>4% of income tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 3. Income &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; –&nbsp;&nbsp;</strong>Rs 5,00,000
            – 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of Tax &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; –&nbsp;</strong>20%<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Health &amp; education cess&nbsp;&nbsp;
                –&nbsp;</strong>4% of income tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 4.
                Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;&nbsp;</strong>More than Rs. 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of
                Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;</strong>30%<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Health &amp; education cess &nbsp;
                &nbsp; –&nbsp;</strong>4% of income tax</p>
        <p>For Senior Citizen (age above 80 years)</p>
        <ol>
            <li><strong>Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; –&nbsp; &nbsp;&nbsp;</strong>Upto Rs
                5,00,000</li>
        </ol>
        <p>Rate of
            Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp; &nbsp;&nbsp; – &nbsp; No Tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 2. Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –</strong>&nbsp;&nbsp; Rs 5,00,000 – 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of Tax &nbsp; &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp; &nbsp;&nbsp; –&nbsp;&nbsp;&nbsp; 20%</strong><br>
            <strong>Health &amp; education cess&nbsp; –&nbsp;&nbsp;</strong>4% of income tax</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 3.
                Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;&nbsp;</strong>More than Rs. 10,00,000<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Rate of
                Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                –&nbsp;</strong>30%<br>
            <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Health &amp; education cess &nbsp;
                –&nbsp;</strong>4% of income tax</p>
        <p>For Domestic Companie</p>
        <ol>
            <li><strong>Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; –&nbsp; &nbsp;&nbsp;</strong>Gross turnover
                upto 250 Cr</li>
        </ol>
        <p>Rate of
            Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp; &nbsp;&nbsp; – &nbsp; 25%</p>
        <p><strong>&nbsp;&nbsp;&nbsp;&nbsp; 2.
                Income&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; –&nbsp; &nbsp;&nbsp;</strong>Gross turnover exceeding
            250 Cr.<br>
            Rate of
            Tax&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp; &nbsp;&nbsp; – &nbsp; 29%</p>

        <h4>Who can file online income tax return</h4>

        <p>Following of the taxpayers can file online income tax return:</p>
        <ul>
            <li>Taxpayers having total income of Rs. 5 lakh and above</li>
            <li>Individual or Hindu undivided family resident with assets located outside India.</li>
            <li>Taxpayer who is required to furnish a report of audit specified under sections 10(23C) (IV),
                10(23C) (v), 10(23C) (VI), 10(23C) (via), 10A, 12A (1) (b), 44AB, 80IA, 80IB, 80IC, 80ID,
                80JJAA, 80LA, 92E or 115JB of the income tax act.</li>
            <li>Firm (not under provisions of Section 44AB), association of person, body of individual,
                artificial juridical person, cooperative society and local authority.</li>
            <li>Taxpayer who is required to furnish return under section 139 (4B) of the income tax return
            </li>
            <li>Resident who has a signing authority in any account located outside India.</li>
            <li>Taxpayer claiming relief under section 90 or 90A or deductions under section 91.</li>
            <li>All companies.</li>
        </ul>
        <h4>Documents Required for Income Tax eFiling</h4>
        <p>
            #1 PAN Card Registration<br>
            #2 Aadhar Number<br>
            #3 Bank Account details<br>
            #4 Form 16<br>
            #5 Form 16A<br>
            #6 Form 26AS<br>
            #7 Investment details<br>
            #8 Rent receipts for claiming house rent allowance<br>
            #9 Bank Passbook<br>
            #10 Fixed deposit statement<br>
            #11 Proof of investment<br>
            #12 Medical expenses receipts, if any<br>
            #13 Proof of home loan interest, if any<br>
            #14 Share transaction statement, if any<br>
            #15 Number Details if any
        </p>

        <h4>Points to be Considered During Efiling of ITR</h4>

        <ul>
            <li>Choose the correct income tax return form</li>
            <li>Clearly identify the heads of income under which it is taxable</li>
            <li>Declare all your assets if your income is more than Rs. 50 lakhs in a year.</li>
            <li>Keep all documents and proofs safe for any future reference.</li>
            <li>Should mention your Aadhar Number</li>
            <li>Study your Form 26AS i.e. tax credit statement</li>
            <li>Check your personal details</li>
            <li>Also add interest income earned from fixed deposits</li>
            <li>Don’t hide any of your source of income</li>
            <li>Report your exempted income</li>
            <li>Should verify your income tax returns</li>
        </ul>

        <h4>FAQs on Income Tax Return</h4>
        <h5>I am a self-employed professional. My income this year is below the minimum income tax slab, but it was
        higher in the previous 2 years and I had filed ITRs then. Do I have to file a return this year?"</h5>
        <p>Ideally, if your income is below the minimum slab, you do not need to file your income tax return. But
        if you have been filing it previously, it would be better if you file a return this year declaring low income.
        This is because the Income Tax Department may construe your non-filing as a delay or non-compliance because of
        your past record of filing ITR. They might send you a notice. In case you do not want to file ITR, be prepared
        to reply to the income tax notice if it comes into your mail box.
        </p>
        <h5>If I have already paid advance taxes and have no dues or refunds, can I skip filing of income tax
        return?</h5>
        <p>No, you have to file your ITR especially if you have paid the taxes. It is not an optional activity. An
        ITR gives the government a complete record of how your income is distributed – assets, total income, tax
        liability, tax paid and refunds. This helps them monitor people for tax fraud of any kind. If you fail to file
        ITR, you are liable to pay penalty or face scrutiny and prosecution.</p>
        <h5>Is an ITR useful to me in daily life?</h5>
        <p> Of course, yes. You’ll find a duly-filed ITR very useful as a proof of income when you have to apply for
        a bank loan, when you have to make accident claims in third party insurance, for immigration and visa, for
        appointment in judicial and class 1 jobs, for winning government tenders, for registration in professional
        panels, for seeking funding for a startup, etc.</p>
        <h5>How long do we need to wait to get income tax refund?</h5>
        <p>Refunds are disbursed only after your ITR is processed. This may take up to 1 year after you file your
        return. It is also possible that even if you are claiming refund, the taxman may have ascertained that you are
        not liable for a refund for various reasons such as a calculation error on your part. If you think your
        calculations are right and you have to get a refund, then you can write to the I-T Department again. Sometimes,
        you do not get a refund because of wrong PAN or bank account number on the ITR, or the cheque not reaching you
        because of wrong address or you not being at home when the postman reached. If you filed your ITR online, you
        can check the status of your refund through your Income Tax e-filing account.</p>
        <h5> Which is the best way to file Income Tax Return?</h5>
        <p>There are multiple ways of filing Income Tax Return. You can file your ITR yourself or take the help of
        a chartered accountant. The easiest way is to file your tax online yourself. You can do so on the website of the
        Income Tax Department. All you have to do is fill the relevant columns on the ITR form and submit it. You can
        also choose to file your ITR using any third-party e-filing website as well. If you find it difficult to file
        your ITR yourself and need expert advice, then it is best to take the help of a chartered accountant.
       </p>
        <h5>Can I File Income Tax Return after Due Date?</h5>
        <p>Yes, you can file your Income Tax Return after the due date. Due to unavoidable circumstances sometimes
        people are unable to file their ITR by the due date. In such cases, they have the option of filing a belated
        return under Section 139 (4) before the end of Assessment Year or before the Assessment is completed (whichever
        is earlier)</p>
        <h5>How to Check the Status of Income Tax Return?</h5>
        <p>Once you file your Income Tax Return, you can check the status of Income Tax Refund on the website of
        the Income Tax Department of India. You can check the status after 10 days, starting from the date the refund is
        sent by entering your Permanent Account Number and selecting the Assessment Year.</p>
        <h5>Which form should use to file Income Tax Return for Salaried Individuals?</h5>
        <p>Individuals who earn income from salary and interest have to fill and submit ITR 1 (SAHAJ) form while
        filing their Income Tax Return.</p>
        <h5>What is Income Tax Return Notice?</h5>
        <p>If you do not file your Income Tax Return in an Assessment Year, then you may receive a notice from the
        Income Tax (IT) Department. The IT Department keeps a track on financial transactions and activities of
        individuals who are identified as non-filers. If there is a discrepancy with the amount of tax that you have
        declared in your ITR, then you may receive a notice from the IT Department. You may also receive a notice if the
        department wants to review any documents related to the ITR that you have filed.</p>
            </div>

    <!--/  content stop /-->









    <!--/ footer Start /-->
    @include('footer');
